{% set name = "collection" %}
{% set year = "2020" %}
{% set cycle = "2" %}
{% set version = "0" %}
{% set micro = "" %}
{% set build_num = "8" %}

package:
  name: {{ name|lower }}
  version: {{ year }}C{{ cycle }}.{{ version }}{{ micro }}

build:
  skip: True  # [py<37 or not linux]
  number: {{ build_num }}

requirements:
  host:
    - python
  run:
    - nsls2-analysis ==2020C2.0=*_{{ build_num }}
    - python
    - ansiwrap
    - bloptools
    - bluesky-darkframes
    - caproto
    - inflection
    - nslsii >=0.1.0
    - pexpect
    - pyepics >=3.4.2
    - pyolog >=4.4.0
    - pyserial
    - python-confluent-kafka  # [not win]
    # Beamline-specific packages
    - chxtools
    - hklpy  # [linux]
    - hxnfly
    - hxntools >=0.4.3
    - ppmac
    # qastools are installed from source
    # - qastools
    - sixtools
    # XPD packages are in conflict with the rest of the stack.
    # Need to fix it on their side.
    # - xpdacq
    # - xpdan
    # Debugging tools:
    - hunter
    - logging_tree
    # Profiling tools:
    - line_profiler
    - pyinstrument

test:
  requires:
    - nsls2forge-utils
  imports:
    - area_detector_handlers
    - bluesky
    - caproto
    - dask
    - databroker
    - event_model
    - lmfit
    - matplotlib
    - napari
    - nslsii
    - numpy
    - ophyd
    - oscars
    - peakutils
    - photutils
    - pymongo
    - pyxrf
    - skbeam
    - srwlpy  # [linux]    
    - srwpy
    - suitcase.csv
    - suitcase.json_metadata
    - suitcase.jsonl
    - suitcase.mongo_embedded
    - suitcase.mongo_normalized
    - suitcase.msgpack
    - suitcase.specfile
    - suitcase.tiff_series
    - suitcase.tiff_stack
    - suitcase.utils
    - xray_vision
    # Beamline-specific packages
    - chxtools
    - csxtools
    - edrixs
    - eiger_io
    - hkl  # [linux]
    - hxntools
    - isstools
    - py4xs
    - sixtools
  commands:
    # Fail if the "conda-forge" channel is in the list of channels.
    - check-results -t channels -f conda-forge  # [not osx]
    # Fail if versions of the packages are not as expected minimum ones.
    - check-results -t version -p bluesky     -e 1.6
    - check-results -t version -p databroker  -e 1.1
    - check-results -t version -p event_model -e 1.16
    - check-results -t version -p nslsii      -e 0.1
    - check-results -t version -p ophyd       -e 1.5
    - python -V
    - ipython -V
    - conda-pack --help
    - napari --help
    - napari --version
    - nexpy --help

about:
  home: https://nsls-ii.github.io/deployment_docs.html
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Collection metapackage for NSLS-II deployments
  description: |
    Collection metapackage for NSLS-II deployments. See the deployment
    documentation at https://nsls-ii.github.io/deployment_docs.html
